[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",

    # enable the atomic codegen option for Xtensa
    "-C",
    "target-feature=+s32c1i",

    # tell the core library have atomics even though it's not specified in the target definition
    "--cfg",
    "target_has_atomic_load_store",
    "--cfg",
    'target_has_atomic_load_store="8"',
    "--cfg",
    'target_has_atomic_load_store="16"',
    "--cfg",
    'target_has_atomic_load_store="32"',
    "--cfg",
    'target_has_atomic_load_store="ptr"',
    # enable cas
    "--cfg",
    "target_has_atomic",
    "--cfg",
    'target_has_atomic="8"',
    "--cfg",
    'target_has_atomic="16"',
    "--cfg",
    'target_has_atomic="32"',
    "--cfg",
    'target_has_atomic="ptr"',
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "--cfg",
    "esp32s3",
    "--cfg",
    "mio_unsupported_force_poll_poll",
    "--cfg",
    "espidf_time64",
]

[build]
#target = "riscv32imc-unknown-none-elf"
target = "xtensa-esp32s3-espidf"

[unstable]
build-std = ["core"]

[env]
MCU = "esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.2"
CROSS_COMPILE = { value = ".embuild/espressif/tools/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin/riscv32-esp-elf", relative = true }
